### PR TITLE
elara04 contribution

### PR DESCRIPTION
**Pull request by elara04**
fixed the syntax issues on the code that was on pycalc-patch 1 
added:
 square root function
log function
natural log function
degrees to radian conversion function
trigonometric function : sin,cos,tan,asin,acos,atan

### CODE REVIEW

**Comment by LoopSoupSnooze** [comment]
Awesome! Thank you for helping! I will include your code for this project!

**Comment by elara04** [comment]
thanks for getting back to me quick, this is my first time contributing, will  git hub it notify me if my code has been merged?

**Comment by LoopSoupSnooze** [comment]
Hello, I have not merge your pull request, to keep it simple and everyone can get back to this Pull-request, I will copy your code and add a new version(update) from the code sections. I'm yet old but also new to GitHub since I didn't really have time to do any coding during school. Nice to have you!

**Comment by elara04** [comment]
awesome thank you for the update. in actually in school right now to learn programing and this is one of the first assignments was to try to go through an opensource repository and  contribute and hopefully get a successful merge. I really appreciate your responsiveness during this process.

**Comment by LoopSoupSnooze** [comment]
That is very cool! I will make sure to include your code, and merge your request! Keep it up and do your best!

**Pull request merged**
