### PR TITLE
Optimise and tidy environment (Issue #2)

### LINKED ISSUE #2: Multi-Calculator - Python 3.6
Multi-Calculator with Python 3
https://github.com/DefGamerGreg/Multi-Calculator.git

I made a multi calculator for learning the concept of programs
Help needed for improvement 
I want to make this calculator more advance and could calculate more than just basic math
I am looking forward for advice 

I will continue to work on this code to make it better, simpler, and advance
I’m pretty new to Python programming 
So helps and attentions are highly needed it

Thanks!
(Read more at Pull request on my homepage)

### PR DESCRIPTION
**Pull request by GemedetAdept**
> Replace individual operation defs with a single, simpler function.

> Replace while loop with more efficient while loop.

> Add option to reload and input another equation.

> Add "modulo" and "floor division" operators to list.

### CODE REVIEW

**Comment by Arghya-Banerjee** [comment]
Assign me this issue. I can provide you with some of the requirements.

**Comment by Arghya-Banerjee** [comment]
One more thing sir. This should be in the issues section rather than pr section as per my knowledge. Please look to it

**Comment by GemedetAdept** [comment]
> Assign me this pr. I can provide you with some of the required review.

> One more thing sir. This should be in the issues section rather than pr section as per my knowledge. Please look to it

Ah! Thank you for letting me know, I'm still getting the hang of all of this. Could you let me know how I'd go about assigning you to it? There's no settings/gear icon on any of the boxes, and I'm not sure how I'd fix that.

**Comment by DefGamerGreg** [comment]
For sure!

**Comment by DefGamerGreg** [comment]
Good luck guys!

**Review by LoopSoupSnooze — COMMENTED** [review]
Thank you!

**Comment by LoopSoupSnooze** [comment]
Sorry, I don’t know why it merged into my branch, I was trying to add this to a new issue

**Comment by LoopSoupSnooze** [comment]
I created a new Pull request, so we can keep working on it together
Please join me so I can assign you to project

I’m new to GitHub, I didn’t know how Merge Pull Request work
XD

**Pull request merged**
